spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/luohanyourena/config-repo.git
          username: luohanyourena
          password: luohan1997126
#          basedir: D:/letter_spring-cloud-clients/config/basedir #配置下载到本地的路径
  rabbitmq:
    host: 192.168.18.73
    port: 5672
    username: guest
    password: guest
eureka:
  client:
    service-url:
#      defaultZone: http://eureka1:8761/eureka/,http://eureka2:8762/eureka/
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
server:
  port: 8083

